// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkg-glednI4f8olknfcSPIeA6Ul2CV9Q0',
    appId: '1:170467822265:web:ac0de830083195d650a968',
    messagingSenderId: '170467822265',
    projectId: 'hastane-randevu-86694',
    authDomain: 'hastane-randevu-86694.firebaseapp.com',
    databaseURL: 'https://hastane-randevu-86694-default-rtdb.firebaseio.com',
    storageBucket: 'hastane-randevu-86694.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgqZx8eIkWf5KkwvukvaC4GZ2U4OUaDa0',
    appId: '1:170467822265:android:160715a95fa4ae9450a968',
    messagingSenderId: '170467822265',
    projectId: 'hastane-randevu-86694',
    databaseURL: 'https://hastane-randevu-86694-default-rtdb.firebaseio.com',
    storageBucket: 'hastane-randevu-86694.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk7oXJVn9X0B976P87OHZigDD8P5uObd8',
    appId: '1:170467822265:ios:b82971ac3e716b1b50a968',
    messagingSenderId: '170467822265',
    projectId: 'hastane-randevu-86694',
    databaseURL: 'https://hastane-randevu-86694-default-rtdb.firebaseio.com',
    storageBucket: 'hastane-randevu-86694.firebasestorage.app',
    iosBundleId: 'com.example.hastaneRandevu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk7oXJVn9X0B976P87OHZigDD8P5uObd8',
    appId: '1:170467822265:ios:b82971ac3e716b1b50a968',
    messagingSenderId: '170467822265',
    projectId: 'hastane-randevu-86694',
    databaseURL: 'https://hastane-randevu-86694-default-rtdb.firebaseio.com',
    storageBucket: 'hastane-randevu-86694.firebasestorage.app',
    iosBundleId: 'com.example.hastaneRandevu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkg-glednI4f8olknfcSPIeA6Ul2CV9Q0',
    appId: '1:170467822265:web:504779ebea28c91750a968',
    messagingSenderId: '170467822265',
    projectId: 'hastane-randevu-86694',
    authDomain: 'hastane-randevu-86694.firebaseapp.com',
    databaseURL: 'https://hastane-randevu-86694-default-rtdb.firebaseio.com',
    storageBucket: 'hastane-randevu-86694.firebasestorage.app',
  );
}
